# Generated by Django 4.0.6 on 2022-08-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_first_last_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_last',
            new_name='last_name',
        ),
    ]
