# Generated by Django 4.0.6 on 2022-08-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-submitted']},
        ),
    ]
