# Generated by Django 4.0.6 on 2022-08-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_rename_first_last_userprofile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_testmonial', to='profiles.userprofile')),
            ],
        ),
    ]
