# Generated by Django 4.0.6 on 2022-08-14 15:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='quote_order_number',
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='size',
            field=models.CharField(choices=[('S', 'Small --- £9.99'), ('M', 'Medium --- £19.99'), ('L', 'Large --- £29.99')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='type',
            field=models.CharField(choices=[('IC', 'Icon --- £9.99'), ('LG', 'Logo --- £19.99'), ('PS', 'Poster --- £39.99'), ('ST', 'Sticker --- £9.99'), ('WP', 'Wallpaper --- £39.99'), ('BN', 'Banner --- £19.99')], max_length=2),
        ),
        migrations.CreateModel(
            name='QuoteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('quote_request_name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('size', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('subtotal', models.CharField(max_length=250)),
                ('discount', models.CharField(max_length=250)),
                ('total', models.CharField(max_length=250)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('quote_order_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stripe_pid', models.CharField(default='', max_length=250)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile')),
            ],
        ),
    ]
