# Generated by Django 4.0.6 on 2022-08-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quoterequest_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='uuid',
        ),
    ]
