# Generated by Django 4.0.6 on 2022-08-14 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_remove_quoterequest_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='quote_request_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
