# Generated by Django 4.0.6 on 2022-08-14 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quoterequest_quote_request_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='quote_request_number',
        ),
        migrations.AlterField(
            model_name='quoteorder',
            name='quote_order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
