# Generated by Django 4.0.6 on 2022-08-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_alter_quoteorder_quote_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteorder',
            name='stripe_pid',
        ),
    ]
