# Generated by Django 4.0.6 on 2022-08-17 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_remove_quoteorder_stripe_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteFufillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.BooleanField(default=False)),
                ('quote_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.quoteorder')),
            ],
        ),
    ]
