# Generated by Django 4.0.6 on 2022-08-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_alter_quotefufillment_quote_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteorder',
            options={'ordering': ['-submitted']},
        ),
    ]
